user:
  outputs:
    default:
      account: GUPLFWW-DM65007
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: DBT_TRIAL
      password: jpf7KGZ-vgn!bxb6tft
      retry_on_database_errors: true
      role: null
      schema: dbt_dhodder
      threads: 6
      type: snowflake
      user: DVHDR
      warehouse: COMPUTE_WH
  target: default
